version: '2'

services:
  mysql:
    image: mysql:5.7
    container_name: dev-mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=dev
      - MYSQL_DATABASE=dev
      - MYSQL_USER=dev
      - MYSQL_PASSWORD=dev

  app:
    image: ambientum/php:7.3-nginx
    container_name: dev-app
    volumes:
      - .:/var/www/app
    ports:
      - "80:8080"
    links:
      - mysql
